name: Build Android Package

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  BUILD_NUMBER: ${{ github.run_number }}
  PYTHON_VERSION: '3.9'  # تغيير إلى الإصدار العام بدلاً من المحدد
  ANDROID_SDK_VERSION: '9477386'
  ANDROID_NDK_VERSION: '25.2.9519653'

jobs:
  build-android:
    runs-on: ubuntu-22.04  # استخدام Ubuntu 22.04 بدلاً من 24.04
    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        architecture: 'x64'

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          git unzip openjdk-17-jdk \
          python3-pip autoconf libtool \
          pkg-config zlib1g-dev libncurses5-dev \
          libncursesw5-dev libtinfo5 cmake \
          libffi-dev libssl-dev

    - name: Install exact Python version
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv venv --python=python3.9
        source venv/bin/activate
        pip install buildozer cython==0.29.33

    - name: Set up Android environment
      uses: android-actions/setup-android@v3
      with:
        ndk-version: ${{ env.ANDROID_NDK_VERSION }}
        sdk-version: ${{ env.ANDROID_SDK_VERSION }}

    - name: Prepare build environment
      run: |
        mkdir -p ./assets
        cp icon.png ./assets/app_icon.png || echo "Icon file not found"
        cp splash.png ./assets/splash.png || echo "Splash file not found"
        echo "buildozer.spec content:"
        cat buildozer.spec || buildozer init

    - name: Build APK
      run: |
        source venv/bin/activate
        buildozer -v android debug
        ls -la ./bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: ./bin/*.apk
        retention-days: 5

    - name: Build AAB
      run: |
        source venv/bin/activate
        buildozer -v android release
        ls -la ./bin/

    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: app-release-aab
        path: ./bin/*.aab
        retention-days: 5
